### ISSUE TITLE
question about multidisplay

### ISSUE THREAD

**Issue by alcasas** [teimor/OpenCore_GA-H97-D3H_RX580#2]
Are you able to see image using 3 displays? 

I installed catalina successfully in my system (i also have the RX580 video card), when I use 2 display everything is good, but when I connect a 3rd one everything goes slowly and the 3rd display doesn't display anything, did you try with 3 displays? thanks

**Comment by nickstock** [comment]
I have three displays on big sur and rx580 all using display port, the third one needed an extra boot arg to work can't remember what it was but the other two were working fine before I added the arg

**Comment by alcasas** [comment]
@nickstock Thanks for your answer. I have the same behavior, 2 displays using display port are working fine and  the 3rd one is not working (black screen) could you share your opencore configuration?

**Comment by teimor** [comment]
Hi, 

I just connected 3rd screen to my setup and it worked without any problem. I used the HDMI Port and two Display Ports near it. 

I don't have another DP monitor to test it, but probably the correct solution to this is create a GPU patch for connector types. If you are using same RX580 as mine (XFX Radeon RX 580 GTS XXX Edition 8GB ) you can create a PR and I will be happy to add it this repo.

[More information about GPU Patching](https://dortania.github.io/OpenCore-Post-Install/gpu-patching/intel-patching/connector.html)

Thanks for the feedback and currently I'm closing this issue.
